name: Node Docker CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run tests (if any)
        run: echo "no tests added"

      # ----------------------
      #  DOCKER BUILD & PUSH
      # ----------------------
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Tag image
        run: docker tag my-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      # ----------------------
      #      DEPLOY TO EC2
      # ----------------------
      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest &&
            docker stop mynode || true &&
            docker rm mynode || true &&
            docker run -d -p 5000:5000 --name mynode ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          "
